export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERR: 'Internal server error',
  BAD_REQUEST: 'Bad request',
  CONFLICT: 'Conflict',
  NOT_FOUND: 'Not found',
  TOO_MANY_REQUESTS: 'Too many requests',
  UNPROCESSABLE_ENTITY: 'Unprocessable entity',
  UNAUTHORIZED: 'Unauthorized',
  USER_NOT_FOUND: 'User not found',
  ROUTE_NOT_FOUND: 'Route not found',
  USER_ALREADY_EXISTS: 'User already exists',
  INVALID_OTP: 'Invalid OTP',
  INVALID_TOKEN: 'Invalid token',
  TOKEN_EXPIRED: 'Token expired',
  EMAIL_OR_PHONE_NOT_VERIFIED: 'Email or Mobile number is not verified',
  INVALID_PASSWORD: 'Invalid password',
  USERAGENT_REQUIRED: 'User-Agent header is required',
  OTP_EXPIRED: 'OTP expired',
  OTP_NOT_REQUESTED: 'OTP not requested or already used',
  ALREADY_LOGGED_IN: 'User already logged in',
  UNKNOWN_ERR: 'Unknown error occurred',
};
